"""attorney and firm tables

Revision ID: 0d7443aca225
Revises: 
Create Date: 2025-06-12 23:15:23.366553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7443aca225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attorney',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('firm', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('patents', sa.Boolean(), nullable=False),
    sa.Column('trademarks', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attorney', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attorney_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_firm'), ['firm'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_patents'), ['patents'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_trademarks'), ['trademarks'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_valid_to'), ['valid_to'], unique=False)

    op.create_table('firm',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('directors', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('patents', sa.Boolean(), nullable=False),
    sa.Column('trademarks', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firm_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_directors'), ['directors'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_patents'), ['patents'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_trademarks'), ['trademarks'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_valid_to'), ['valid_to'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_valid_to'))
        batch_op.drop_index(batch_op.f('ix_firm_valid_from'))
        batch_op.drop_index(batch_op.f('ix_firm_trademarks'))
        batch_op.drop_index(batch_op.f('ix_firm_phone'))
        batch_op.drop_index(batch_op.f('ix_firm_patents'))
        batch_op.drop_index(batch_op.f('ix_firm_name'))
        batch_op.drop_index(batch_op.f('ix_firm_id'))
        batch_op.drop_index(batch_op.f('ix_firm_email'))
        batch_op.drop_index(batch_op.f('ix_firm_directors'))
        batch_op.drop_index(batch_op.f('ix_firm_address'))

    op.drop_table('firm')
    with op.batch_alter_table('attorney', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attorney_valid_to'))
        batch_op.drop_index(batch_op.f('ix_attorney_valid_from'))
        batch_op.drop_index(batch_op.f('ix_attorney_trademarks'))
        batch_op.drop_index(batch_op.f('ix_attorney_phone'))
        batch_op.drop_index(batch_op.f('ix_attorney_patents'))
        batch_op.drop_index(batch_op.f('ix_attorney_name'))
        batch_op.drop_index(batch_op.f('ix_attorney_id'))
        batch_op.drop_index(batch_op.f('ix_attorney_firm'))
        batch_op.drop_index(batch_op.f('ix_attorney_email'))
        batch_op.drop_index(batch_op.f('ix_attorney_address'))

    op.drop_table('attorney')
    # ### end Alembic commands ###
