"""external id and indexing

Revision ID: 41ff28f19830
Revises: 0d7443aca225
Create Date: 2025-06-13 00:20:14.997049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ff28f19830'
down_revision = '0d7443aca225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attorney', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_attorney_address'))
        batch_op.drop_index(batch_op.f('ix_attorney_id'))
        batch_op.drop_index(batch_op.f('ix_attorney_patents'))
        batch_op.drop_index(batch_op.f('ix_attorney_phone'))
        batch_op.drop_index(batch_op.f('ix_attorney_trademarks'))
        batch_op.create_index(batch_op.f('ix_attorney_external_id'), ['external_id'], unique=False)

    with op.batch_alter_table('firm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_firm_address'))
        batch_op.drop_index(batch_op.f('ix_firm_id'))
        batch_op.drop_index(batch_op.f('ix_firm_patents'))
        batch_op.drop_index(batch_op.f('ix_firm_phone'))
        batch_op.drop_index(batch_op.f('ix_firm_trademarks'))
        batch_op.create_index(batch_op.f('ix_firm_external_id'), ['external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_external_id'))
        batch_op.create_index(batch_op.f('ix_firm_trademarks'), ['trademarks'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_patents'), ['patents'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_address'), ['address'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('external_id')

    with op.batch_alter_table('attorney', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attorney_external_id'))
        batch_op.create_index(batch_op.f('ix_attorney_trademarks'), ['trademarks'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_patents'), ['patents'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_address'), ['address'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
