"""table renames and firm website field

Revision ID: 8b6547fdde8a
Revises: 41ff28f19830
Create Date: 2025-06-14 22:25:11.728000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6547fdde8a'
down_revision = '41ff28f19830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attorneys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('firm', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('patents', sa.Boolean(), nullable=False),
    sa.Column('trademarks', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attorneys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attorneys_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorneys_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorneys_firm'), ['firm'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorneys_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorneys_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorneys_valid_to'), ['valid_to'], unique=False)

    op.create_table('firms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('directors', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('patents', sa.Boolean(), nullable=False),
    sa.Column('trademarks', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firms_directors'), ['directors'], unique=False)
        batch_op.create_index(batch_op.f('ix_firms_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_firms_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firms_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_firms_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_firms_valid_to'), ['valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_firms_website'), ['website'], unique=False)

    with op.batch_alter_table('firm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firm_directors'))
        batch_op.drop_index(batch_op.f('ix_firm_email'))
        batch_op.drop_index(batch_op.f('ix_firm_external_id'))
        batch_op.drop_index(batch_op.f('ix_firm_name'))
        batch_op.drop_index(batch_op.f('ix_firm_valid_from'))
        batch_op.drop_index(batch_op.f('ix_firm_valid_to'))

    op.drop_table('firm')
    with op.batch_alter_table('attorney', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attorney_email'))
        batch_op.drop_index(batch_op.f('ix_attorney_external_id'))
        batch_op.drop_index(batch_op.f('ix_attorney_firm'))
        batch_op.drop_index(batch_op.f('ix_attorney_name'))
        batch_op.drop_index(batch_op.f('ix_attorney_valid_from'))
        batch_op.drop_index(batch_op.f('ix_attorney_valid_to'))

    op.drop_table('attorney')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attorney',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('firm', sa.VARCHAR(length=128), nullable=True),
    sa.Column('address', sa.VARCHAR(length=128), nullable=True),
    sa.Column('patents', sa.BOOLEAN(), nullable=False),
    sa.Column('trademarks', sa.BOOLEAN(), nullable=False),
    sa.Column('valid_from', sa.DATE(), nullable=False),
    sa.Column('valid_to', sa.DATE(), nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attorney', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attorney_valid_to'), ['valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_firm'), ['firm'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attorney_email'), ['email'], unique=False)

    op.create_table('firm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('directors', sa.VARCHAR(length=256), nullable=True),
    sa.Column('address', sa.VARCHAR(length=128), nullable=True),
    sa.Column('patents', sa.BOOLEAN(), nullable=False),
    sa.Column('trademarks', sa.BOOLEAN(), nullable=False),
    sa.Column('valid_from', sa.DATE(), nullable=False),
    sa.Column('valid_to', sa.DATE(), nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firm_valid_to'), ['valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_valid_from'), ['valid_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_firm_directors'), ['directors'], unique=False)

    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firms_website'))
        batch_op.drop_index(batch_op.f('ix_firms_valid_to'))
        batch_op.drop_index(batch_op.f('ix_firms_valid_from'))
        batch_op.drop_index(batch_op.f('ix_firms_name'))
        batch_op.drop_index(batch_op.f('ix_firms_external_id'))
        batch_op.drop_index(batch_op.f('ix_firms_email'))
        batch_op.drop_index(batch_op.f('ix_firms_directors'))

    op.drop_table('firms')
    with op.batch_alter_table('attorneys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attorneys_valid_to'))
        batch_op.drop_index(batch_op.f('ix_attorneys_valid_from'))
        batch_op.drop_index(batch_op.f('ix_attorneys_name'))
        batch_op.drop_index(batch_op.f('ix_attorneys_firm'))
        batch_op.drop_index(batch_op.f('ix_attorneys_external_id'))
        batch_op.drop_index(batch_op.f('ix_attorneys_email'))

    op.drop_table('attorneys')
    # ### end Alembic commands ###
