"""Foreign key fields

Revision ID: b440385ff79e
Revises: a0f9a4d8b344
Create Date: 2025-08-26 00:18:34.654876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b440385ff79e'
down_revision = 'a0f9a4d8b344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attorneys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firm_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_attorneys_firm_id'), ['firm_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_attorneys_firm_id_firms'), 'firms', ['firm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attorneys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attorneys_firm_id_firms'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_attorneys_firm_id'))
        batch_op.drop_column('firm_id')

    # ### end Alembic commands ###
