"""New firms table

Revision ID: e0889df2aa48
Revises: b440385ff79e
Create Date: 2026-02-21 20:52:09.159678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0889df2aa48'
down_revision = 'b440385ff79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consolidated_firms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consolidated_firms'))
    )
    with op.batch_alter_table('consolidated_firms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consolidated_firms_name'), ['name'], unique=False)

    with op.batch_alter_table('attorneys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consolidated_firm_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_attorneys_firm_id'))
        batch_op.create_index(batch_op.f('ix_attorneys_consolidated_firm_id'), ['consolidated_firm_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_attorneys_firm_id_firms'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attorneys_consolidated_firm_id_consolidated_firms'), 'consolidated_firms', ['consolidated_firm_id'], ['id'])
        batch_op.drop_column('firm_id')

    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consolidated_firm_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_firms_consolidated_firm_id'), ['consolidated_firm_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_firms_consolidated_firm_id_consolidated_firms'), 'consolidated_firms', ['consolidated_firm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_firms_consolidated_firm_id_consolidated_firms'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_firms_consolidated_firm_id'))
        batch_op.drop_column('consolidated_firm_id')

    with op.batch_alter_table('attorneys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firm_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_attorneys_consolidated_firm_id_consolidated_firms'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_attorneys_firm_id_firms'), 'firms', ['firm_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_attorneys_consolidated_firm_id'))
        batch_op.create_index(batch_op.f('ix_attorneys_firm_id'), ['firm_id'], unique=False)
        batch_op.drop_column('consolidated_firm_id')

    with op.batch_alter_table('consolidated_firms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consolidated_firms_name'))

    op.drop_table('consolidated_firms')
    # ### end Alembic commands ###
